version: '3.1'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 19840619
    ports:
      - "3306:3306"
    volumes:
      - my-data:/var/lib/mysql

volumes:
  my-data: